### ISSUE TITLE
Chrome - unable to unzip extension

### ISSUE THREAD

**Issue by Jmasterton-Rentokil** [toasterco/Quiz-Master-for-Google-Meet#10]
As above. Attempts to install the extension from the Chrome Web Store throws up an "unable to unzip" error, which suggests a packaging error. Can you assist?
![Screenshot 2022-06-14 09 24 17](https://user-images.githubusercontent.com/107466210/173530309-a3bffcfe-2825-467e-9eea-20df5393910e.png)

**Comment by skezo** [comment]
@Jmasterton-Rentokil thanks for flagging this. 
We can replicate the issue. We are looking into it now.

**Comment by skezo** [comment]
@Jmasterton-Rentokil we have pushed a new version 0.7.7 which seems to be fine. It should hopefully be published in the next 48hrs. We will keep this open until we can confirm we can install the extension.
Thanks again for flagging this.

**Comment by skezo** [comment]
@Jmasterton-Rentokil 
Should be live now and working. Please confirm.

**Comment by Jmasterton-Rentokil** [comment]
Pleased to report the error is resolved and the extension is installable.
