### ISSUE TITLE
text not dark-mode friendly

### ISSUE THREAD

**Issue by jergo123** [toasterco/Quiz-Master-for-Google-Meet#5]
Hey, I use Opera GX which has kind of a dark mode feel. With this, some of your black and purple text is really hard to see.
![imagen_2021-03-26_155452](https://user-images.githubusercontent.com/81439906/112680002-99dcae00-8e4b-11eb-8f8c-32552019215b.png)

**Comment by skezo** [comment]
Thanks for creating this issue.
We've pushed an update for this (v0.6.9) which should fix this issue. If it is still happening please us know if you have any other extensions installed, the OS you are using etc. This will help us replicate your environment.

![Screenshot 2021-03-29 at 10 31 55 AM](https://user-images.githubusercontent.com/793287/112779787-1359e380-907a-11eb-85d3-24b4c77d94b9.png)
