### ISSUE TITLE
Quiz Master is not working on google meet

### ISSUE THREAD

**Issue by YashGarg10** [toasterco/Quiz-Master-for-Google-Meet#7]

**Comment by skezo** [comment]
@YashGarg10

Thanks for raising this ticket. Could you please share a screen shot of your google meet?  We can then look into it.
Google Meet is in the process of doing a global rollout so there are few different versions right now.

**Comment by YashGarg10** [comment]
![Screenshot (74)](https://user-images.githubusercontent.com/84704942/119333376-6b424e80-bca7-11eb-9448-9736b6b56c70.png)

**Comment by steveglachan** [comment]
I'm getting the same experience. Cannot see a 'dice' as the instructions say.

**Comment by skezo** [comment]
@steveglachan @YashGarg10 

Version 0.7.3 should fix this problem. The dice icon will be found on the bottom right corner.
<img width="353" alt="Screenshot 2021-08-31 at 1 26 13 PM" src="https://user-images.githubusercontent.com/793287/131446985-c32ef004-0821-4831-bde5-6db7ddb5a748.png">
